import type { Metadata } from "next";

import "./globals.css";
import Slid from "./components/Slid";
import Footer from "./components/Footer";
import { CartProvider } from "@/context/Context"
import Header from "./components/Header";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartProvider>
      <html lang="en">
        <body>
          <Header />
          {children}
          <Slid />
          <Footer />
        </body>
      </html>
    </CartProvider>
  );
}
